### ISSUE TITLE
[solr] can't find values for basic authentication configuration

### ISSUE THREAD

**Issue by pengfei99** [PreferredAI/helm-charts#13]
Hi all,

Thanks for your good work. This is not a bug report.

I used this chart to deploy a solr cluster. It works well. But I can't find any configuration in values.yaml for basic authentication.

Is it normal? Or I have to do it by my self by using init script?

Thanks

**Comment by lwj5** [comment]
Hi PengFei,

I'm planning to put this in soon but I can't give you an ETA, it would be best to replace security.json directly using `solr zk cp` to replace the file from one of the nodes.

Coincidentally, we were just testing out basic auth today but we faced some issues. You will need to turn the current health check off (using values.yaml), or switch to non HTTP health checks (currently not available in values.yaml). Solr will return 401 after security is enabled and this will kill the pod.

I'll leave this issue open for now so can track the enhancement here. Cheers.

**Comment by pengfei99** [comment]
Hi Ween,

Thanks for the quick reply. I will test your solution.

Hope you can resolve your pb very soon

Have a nice day

BR

Pengfei

**Comment by pengfei99** [comment]
Hi,
I can't turn the current health check off by setting 

livenessProbe:
    enabled: false
    
readinessProbe:
    enabled: false

What do I need to do to set the health check off?

Thanks 

Pengfei

**Comment by pengfei99** [comment]
Hi, 

I just take a took at the template source code, 

livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.livenessProbe.successThreshold }}
            failureThreshold: {{ $.Values.livenessProbe.failureThreshold }}
            httpGet:
              scheme: "{{ .Values.tls.enabled | ternary "HTTPS" "HTTP" }}"
              path: /solr/admin/info/system
              port: {{ .Values.port }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.readinessProbe.successThreshold }}
            failureThreshold: {{ $.Values.readinessProbe.failureThreshold }}
            httpGet:
              scheme: "{{ .Values.tls.enabled | ternary "HTTPS" "HTTP" }}"
              path: /solr/admin/info/system
              port: {{ .Values.port }}

There is no if check on enabled, that's why it does not work

**Comment by lwj5** [comment]
Yes, I just saw it too. I have a PR merging in #14. Give it 5min

**Comment by pengfei99** [comment]
Great, 

Thanks a lot
