### ISSUE TITLE
[SOLR] EKS Fargate Support

### ISSUE THREAD

**Issue by PhilippeTrounev** [PreferredAI/helm-charts#27]
**Affected chart**
Solr-3.0.3

**Is your feature request related to a problem? Please describe.**
I wanted to run existing Helm on EKS Fargate, the problem is it fails with 
`FailedScheduling Pod not supported on Fargate: volumes not supported: solr-pvc not supported because: PVC solr-pvc-solr-0 not bound`

**Describe the solution you'd like**
I would like to see support for AWS EFS CSI driver. Maybe this is nonesense and helm already supports it, but I couldn't figure it out. 

**Describe alternatives you've considered**
Alternatie is to keep running on EKS which is fine, but Fargate would be a better option due to infinite scalability. 

**Additional context**
Not sure

**Comment by lwj5** [comment]
Please read https://aws.amazon.com/blogs/containers/running-stateful-workloads-with-amazon-eks-on-aws-fargate-using-amazon-efs/ under "StatefulSets with Amazon EFS"

Please track https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/274 and wait for EFS CSI to support StatefulSets.

This is an EKS on Fargate issue. Will proceed to close.

**Comment by carlosrmendes** [comment]
@lwj5 that is an EKS on Fargate issue only for the dynamic provision of PVCs... I may want just to use an already existing PVC (with EFS storageclass) but with the current templating structure I'm not able to specify that on the values.yaml... so, I suggest to put the `volumeClaimTemplates` spec optional on the statefulset so I can specify the exiting PVC using the `extraVolumes` and `extraVolumeMounts` values

**Comment by lwj5** [comment]
@carlosrmendes that’s a good idea, feel free to create a PR for it. I’ll approve the changes

**Comment by carlosrmendes** [comment]
done #29 
thanks @lwj5
