### ISSUE TITLE
[Solr] Migrate between Charts

### ISSUE THREAD

**Issue by pai911** [PreferredAI/helm-charts#32]
Hi!

I installed the old version Solr chart (https://github.com/helm/charts/tree/master/incubator/solr) last year

and when I came back, it seemed the Chart does no longer exist.

It looks like this one is the descendent of the old one.

But now I am kinda stuck in how to migrate my old Chart to this one...

Is there a guide on how to migrate charts?

Thanks!

**Comment by lwj5** [comment]
Hi there,

There’s not much to do except to move the folders into a data subfolder detailed in #5 for every solr volume.

Then upgrade the chart to this one.

let me know if there’s any issues along the way.
