### ISSUE TITLE
[solr] 3.2.0 chart - templatize repo/image name for check-zk container in /solr/templates/statefulset.yaml

### ISSUE THREAD

**Issue by pstrex** [PreferredAI/helm-charts#33]
Currently in 3.2.0 chart repo/image name of check-zk container is hardcoded into solr/templates/statefulset.yaml
It would be great if you could templatize that info so we can pull this image from our local repository instead of docker.io which is subject to rate limiting.

Thanks,
Marcin

**Comment by lwj5** [comment]
Hey there,

Sure thing. I'll take a look at it next week. If you need it sooner, feel free to make a PR!
